#!/usr/bin/env bash
# install and configures HAproxy
sudo apt-get update
sudo apt-get -y install haproxy=1.6.\*

echo "frontend http
        bind *:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
        server webserver1 34.74.218.233:80 check
        server webserver2 54.221.13.105:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
