#!/usr/bin/env bash
# write Holberton School 10 times , but bad luck for 4th and good luck for 8th
n=1
while [ $n -le 10 ]
do
    if [ $n == 4 ]
    then
	echo "bad luck"
    elif [ $n == 8 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    let n++
done
